model:
  url: https://coding.dashscope.aliyuncs.com/v1
  apiKey: 123456
  name: your-model-name

embedding:
  model:
    url: https://coding.dashscope.aliyuncs.com/v1
    apiKey: 123456
    name: your-embedding-name

# port
server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

